model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
suppress_unstable_features_warning = true
web_search = "live"

[sandbox_workspace_write]
network_access = true

[features]
unified_exec = true
shell_snapshot = true
collab = true
collaboration_modes = true
steer = true

[notice]
hide_rate_limit_model_nudge = true